
name: CI/CD Pipeline to AWS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ubuntu
          POSTGRES_PASSWORD: ubuntu1111
          POSTGRES_DB: githubactions
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U ubuntu -d githubactions"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Debug Environment Variables
        run: env | sort

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run migrations
        env:
          DATABASE_URL: postgres://ubuntu:ubuntu1111@localhost:5432/githubactions
        run: |
          source venv/bin/activate
          python manage.py migrate

      - name: Collect static files
        env:
          DATABASE_URL: postgres://ubuntu:ubuntu1111@localhost:5432/githubactions
        run: |
          source venv/bin/activate
          python manage.py collectstatic --noinput

      - name: Run tests
        env:
          DATABASE_URL: postgres://ubuntu:ubuntu1111@localhost:5432/githubactions
        run: |
          source venv/bin/activate
          python manage.py test


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          #chmod 700 ~/.ssh
          #echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          #chmod 600 ~/.ssh/id_rsa
          #ssh-keyscan -H 13.53.113.230 >> ~/.ssh/known_hosts

      - name: Deploy to AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@13.53.113.230 '
          cd /home/ubuntu/github-django-actions &&
          git pull origin master &&
          source venv/bin/activate &&
          pip install -r requirements.txt &&
          python manage.py migrate &&
          python manage.py collectstatic --noinput &&
          sudo systemctl restart gunicorn &&
          sudo systemctl restart nginx'
